Repository cloudfoundry-incubator/bits-service-release, pull requests merged in 2019-05, with the labels that each got.

#22 Separate bits helm chart
  helm/bits-0.0.0-dev.tgz
  helm/bits/Chart.yaml
  helm/bits/README.md
  helm/bits/templates/NOTES.txt
  helm/bits/templates/_helpers.tpl
  helm/bits/templates/bits.yaml
  helm/bits/values.yaml
  helm/index.yaml
Labels: unscheduled

#26 Restart policy is not part of the container spec
  helm/bits/templates/bits.yaml
Labels: scheduled

#28 Set correct restartPolicy for Bits deployment
  helm/bits/templates/bits.yaml
Labels: unscheduled

#29 Drop bits-service.rootfs.blobstore_type property
  jobs/bits-service/spec
  jobs/bits-service/templates/bits_config.yml.erb
Labels: unscheduled

#27 Add BPM support
  jobs/bits-service/monit
  jobs/bits-service/spec
  jobs/bits-service/templates/bits_config.yml.erb
  jobs/bits-service/templates/bpm.yml.erb
Labels: in progress
